name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ref
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: wiremock/grpc-wiremock:${{ github.ref_name }}
      - name: Build and push latest
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: wiremock/grpc-wiremock:latest
